port: 3000
logger-output-path: "./output/file.txt"

oauthStateString: "thisshouldberandom"
google:
  clientID: "google client id"
  clientSecret: "google client secret"
facebook:
  clientID: "facebook client id"
  clientSecret: "facebook client secret"
microsoft:
  clientID: "bfee93bf-32a7-4793-bfe0-7e052aa5d85c"
  clientSecret: "ojK7Q~9RRw-CIZY3yECxpHfSIn-EFkM6QoLoi"
  tenant: "64042d1e-5184-4768-9ba5-2a3fa3f4bd69"
