port: 3000
logger-output-path: "./output/file.txt"

oauthStateString: "thisshouldberandom"

microsoft:
  clientID: "bfee93bf-32a7-4793-bfe0-7e052aa5d85c"
  clientSecret: "ojK7Q~9RRw-CIZY3yECxpHfSIn-EFkM6QoLoi"
  tenant: "64042d1e-5184-4768-9ba5-2a3fa3f4bd69"
  scopes: 
    - "api://bfee93bf-32a7-4793-bfe0-7e052aa5d85c/access_as_user"
  issuer: "https://sts.windows.net/090d1a76-b650-431c-b493-e1e446dc2039/"
